"""
Django settings for django_visual project.

Generated by 'django-admin startproject' using Django 1.11.20.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# import django_heroku

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TOP_DIR = os.path.abspath(os.path.join(BASE_DIR, os.pardir))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 't@-^$$tlw0gav=lp38^l_8g-(xo88&td-(f4*_uc=_6c#pcsa='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.staticfiles',
    'ide',
]

MIDDLEWARE = [
]

ROOT_URLCONF = 'django_visual.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
            ],
        },
    },
]

TEMPLATE_CONTEXT_PROCESSORS = (
    'django.template.context_processors.debug',
    'django.template.context_processors.request',
)

TEMPLATE_LOADERS = (
    'django.template.loaders.filesystem.Loader',
    'django.template.loaders.app_directories.Loader',
)

WSGI_APPLICATION = 'django_visual.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


AUTH_PASSWORD_VALIDATORS = [
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

# STATIC_ROOT = os.path.join(BASE_DIR, "static")

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

PROJECTS_HOME = os.path.join(TOP_DIR, 'projects')
TEMPLATES_HOME = os.path.join(BASE_DIR, 'conf')

PROJECTS_TEMPLATES = [
    ("empty", "Empty Project", "New Django project with default configuration. <br />Same as running 'django-admin startproject' from terminal."),
    ("blog", "Blog", "Blog project starts with main page and blog posts list on it. <br />Admin panel included to edit blog entries."),
    ("cms", "Web Site", "Starting point for content site. Includes main page, <br />items list and item detail page. Preconfigured with <br />'Contact Us' and 'About' pages as well as admin panel."),
    ("app", "1-Page Application", "One page web application project. <br />Preconfigured index page template based on Bootstrap 4.")
]

PROJECT_NAMES = ['shiny', 'crazy', 'frog', 'squirrel', 'nut', 'bold',
    'hamster', 'blog', 'site', 'red', 'dead', 'last', 'first', 'super', 'cool',
    'brilliant', 'py', 'web', 'app', 'hello'
]

# STATIC_URL = '/static/'

# STATIC_ROOT = os.path.join(BASE_DIR, "static")

# django_heroku.settings(locals())
